### PR TITLE
Fix foreground issues and added CI

### PR DESCRIPTION
**Pull request by vikeri**

### CODE REVIEW

**Comment by Jacse** [comment]
My app keeps on firing the background job upon launch in dev mode. Will this fix it, @vikeri? If so could it be merged?

**Comment by vikeri** [comment]
@Jacse The foreground jobs will still launch when you reload the js without reopening the whole app. But that should not be an issue in production. This is released as `react-native-background-job@1.2.4-0` if you wan't to try it out.

**Comment by Jacse** [comment]
This is still an issue in productionm @vikeri. Using `react-native-background-job@1.2.4-0`. Screengrab from Bugsnag:

Bugsnag screen grab

**Comment by i6mi6** [comment]
I also got the error in production

**Comment by vikeri** [comment]
@Jacse & @i6mi6 any reason you're not using the latest `2.X.X` release?

**Comment by Jacse** [comment]
@vikeri I don't think it was released when I made my comment 😄  I recently updated, though, and I'm afraid it seems to still be happening. I'll publish an update to my app soon and then I'll re-confirm after having upgraded to the newest React Native etc. too.

**Comment by vikeri** [comment]
@Jacse Unforturnately there seems to be issues with the latest RN version. The version in the example project should work though.

**Comment by vikeri** [comment]
@maheshsgr Could you try with version `2.2.0-beta` and see if you still have the issue?

**Pull request merged**
