### PR TITLE
Remove deprecated createJSModules @Override

### PR DESCRIPTION
**Pull request by piuholo**
Breaking changes in React Native 0.47

facebook/react-native@ce6fb33

### CODE REVIEW

**Comment by vikeri** [comment]
Great! Is this backwards compatible?

**Comment by beeglebug** [comment]
It is yeah, i've seen the exact same change merged into a dozen of my dependencied in the last few days, and raised an identical one myself (https://github.com/mikemonteith/react-native-android-checkbox/pull/14)

**Comment by piuholo** [comment]
Yes, the change is backwards compatible, as we only remove the Override marker

**Comment by holyxiaoxin** [comment]
Please merge this @vikeri (:

**Pull request merged**
