### PR TITLE
update iOS headers for RN 0.40

### PR DESCRIPTION
**Pull request by freakinruben**

### CODE REVIEW

**Comment by vikeri** [comment]
Thanks! I'll test this out asap!

**Comment by freakinruben** [comment]
I only now notice that the java and iOS code are very different.. This is basically an android only lib?

**Comment by vikeri** [comment]
Yeah, before someone implements HeadlessJS for iOS this only works for Android unfortunately: https://productpains.com/post/react-native/headless-js-for-ios

**Comment by vikeri** [comment]
Finally got around to test this, I couldn't get it to compile for pre 0.40, is that expected or can it somehow be made backwards compatible?

**Comment by atlanteh** [comment]
Yes. All rn libraries needed a major jump because of this.
See [react-native-fcm](https://github.com/evollu/react-native-fcm) for example

**Comment by freakinruben** [comment]
I looked at how code-push did it so I figured it would be backwards compatible.. [Reference](https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePush.h)

**Comment by vikeri** [comment]
This does not seem to be an issue anymore.

**Pull request closed without merging**
