### PR TITLE
add allowedInForeground option

### PR DESCRIPTION
**Pull request by cbjs**

### CODE REVIEW

**Comment by vikeri** [comment]
I don't think this is the way to solve this, if you run jobs in the foreground they will freeze the UI: https://facebook.github.io/react-native/docs/headless-js-android.html#caveats

And when you are in the foreground a normal setTimeout or setInterval works. I'm going to investigate the foreground issue some more, I thought I had added enough checks, but apparently not.

**Comment by nonsense66** [comment]
This would actually fix some crashes for my app. I vote to merge it.

**Comment by vikeri** [comment]
Ideally I'd like to debug where the actual crash happens, but this option is at least better than allowing it to run in the foreground by default. But this PR needs to be updated first. If it is, then I'll merge it.

**Comment by nonsense66** [comment]
@vikeri what needs to be done? maybe I can help?

**Comment by vikeri** [comment]
This has been solved by the new flag `allowExecutionInForeground` in 2.0.0, see [docs](https://github.com/vikeri/react-native-background-job#schedule)

**Pull request closed without merging**
