### PR TITLE
Migrate from JobScheduler to firebase-jobdispatcher

### PR DESCRIPTION
**Pull request by toteto**
Many changes compared to the original version, mainly on the native side. The method signatures remained mostly the same, removed few parameters that were obsolete. 

Started with migrating to the firebase-jobdispatcher that is meant as a compatibility library to the JobScheduler. With this migration there is no need to raise the minSdk version from 16 to 21. 

The logic on the native side when using regular background job is very simple and maintainable. The proprietary scheduler with AlarmManager (replacement for foregroundService) is only there to provide more precise scheduling while debugging and it didn't invest too much time on it.

I have tested this with multiple versions of Android (5.0, 6.0 and 7.0) and latest react-native 0.45.1 and it is working very good.

### CODE REVIEW

**Comment by mauriciopasquier** [comment]
What about enviroments without google play? Or offline jobs/apps? Jobs wouldn't work in those cases, right?

PD: Sorry if I missed something obvious, just starting with android here.

**Comment by toteto** [comment]
@mauriciopasquier Yes the device must have Google Play Services in order the library to work.

Offline jobs will work fine, this is a job dispatcher not cloud messaging.

**Comment by mauriciopasquier** [comment]
Thanks for answering!

**Comment by vikeri** [comment]
Thanks a lot for this, looks really good! 
A couple of questions:
- For compatible versions, does firebase use the native JobScheduler?
- The taskId parameter does not seem to be needed by the firebase version, how do I then debug using: `adb shell cmd jobscheduler run -f com.backtest 567642`?
- Does the firebase version address issues like the network parameters not being respected sometimes for the JobScheduler?
- I see you removed the `alwaysRunning` option. We're actually abandoning it in our team for the moment as well, but I'd still like to keep it since it opens up a whole different set of use cases. Could it be restored?
- Does this address #17 ?
- Any particular reason for removing `getAll()`?
- Did the js go through prettier and the documentation regenerate using document? It should have been a pre-commit hook. Not sure if it ran though?

**Comment by toteto** [comment]
Thank you also for your support while development.
- For compatible versions, does firebase use the native JobScheduler? - _**From the readme of the firebase-jobdispather it is mentioned that: "This library uses the scheduling engine inside Google Play services(formerly the GCM Network Manager component) to provide a backwards compatible (back to Gingerbread) JobScheduler-like API."**_

- Does the firebase version address issues like the network parameters not being respected sometimes for the JobScheduler? - _**I have tried the network filtering and it works on Nougat. It is not mentioned anywhere in the documentation that it is not respected by particular version. Since it relies on Google Play Services, it should have the same behavior on KitKat as on Nougat**._

- I see you removed the alwaysRunning option. We're actually abandoning it in our team for the moment as well, but I'd still like to keep it since it opens up a whole different set of use cases. Could it be restored? - _**I would strongly prefer not to, because such notification will keep wake lock on the device and drain the battery. For a use case when notification should be displayed when some job is performed, the combo of some notification library and this one should get the job done.**_

- Does this address #17 ? - _**From my testing I didn't experience such issue.  If you check [ReactNativeEventStarter.java](https://github.com/toteto/react-native-background-job/blob/460ebc564c1f534a56e2a0d265f0e2b72648b241/android/src/main/java/com/pilloxa/backgroundjob/ReactNativeEventStarter.java#L27-L35), right before the task is created, it is checked if the app is in foreground.**_

- Any particular reason for removing getAll()? - _**There is no such method in the firebase implementation. The parameter `override` should allow the developer to skip already scheduled jobs.**_

- Did the js go through prettier and the documentation regenerate using document? It should have been a pre-commit hook. Not sure if it ran though? - _**I am sure it went through the documentation (you can check the README.md), not sure about prettier.**_ 

- The taskId parameter does not seem to be needed by the firebase version, how do I then debug using: adb shell cmd jobscheduler run -f com.backtest 567642? - _**Not sure about this**_

**Comment by jussisaurio** [comment]
The `alwaysRunning` option is very relevant for the use case I'm developing for right now, so I would definitely suggest keeping it as an available option.

**Comment by toteto** [comment]
@jussisaurio Can you tell me what is the use case that requires the `alwaysRunning` and can't be replaced by notification + job with `exact` set to `true`?

**Comment by brafdlog** [comment]
I also use the always running. My app monitors the sensors of the device constantly and it is very important that it will keep running in the background 24/7. So for me it is an important option.

**Comment by toteto** [comment]
@brafdlog And how that can't be achieved with `exact` set to `true`?

**Comment by jussisaurio** [comment]
@toteto My app needs to listen for and record the data of notification events sent by an external sensor device at intervals decided by the external device. It should be possible to leave it on overnight recording.

**Comment by toteto** [comment]
@jussisaurio 
The previous implementation used native foreground service that used Timer to trigger event of your job. 

In this one when you use the exact job option, AlarmManager it is used to trigger your scheduled job. 

Basically, the previous alwaysRunning job == exact job without the notification.

**Comment by vikeri** [comment]
I would really like to merge this PR, @toteto how frequently can you run the job if you have exact set to true?

**Comment by toteto** [comment]
@vikeri In the new version of the example app, both of the exact jobs are scheduled to execute every second (1000ms). The is no limitation on how short it can be.

The PR has been tested by my team and for now it is stable. There are 2 small things i need to check, but nothing critical.

**Comment by vikeri** [comment]
Ok, if it's scheduled to run every 1000ms it basically means that Android will never kill the app and it will be on forever anyway. I'm very against the concept of breaking the API of an open source library, but for this purpose it might be worth it. It will mean a major version bump. I'm going to merge my PR, release the last version of 1.x.x and then revert the things in master that I did so that this PR can be merged without major conflicts.

But first, could you resolve the current merge conflict?

**Comment by toteto** [comment]
@vikeri it has been merged with the master branch of your repository. Because the whole BackgroundJobModule has been rewritten, there were no functional changes from the merge.

Fixed one bug when an exact job was scheduled with short periodicity, the user had high chance to hit the point before the app in foreground check and the actual HeadlessJsTaskService launch.

Have you tested this PR with your app?

**Comment by vikeri** [comment]
Great, no it was just to resolve the merge conflict. I have not tested it yet. Will probably do it in the upcoming week. If it works then I'll merge it 👍

**Comment by vikeri** [comment]
For people keen on testing this I published it as a beta to `react-native-background-job@2.0.0-0`. Will do some testing and if it works as expected I'll merge it and bump the version to `2.0.0`

**Comment by brafdlog** [comment]
@toteto In my use case I register callbacks to sensors. These callbacks run when the sensors have data, not when the job is running. So I basically need to keep the app alive all the time. The always running flag did just that and that was great.
Running with exact true won't keep my app alive in the background, it will just run it in intervals right?
If this really can't be done with exact, why not leave the always running option? I understand it drains the battery but in some use cases that is what you need.

**Comment by vikeri** [comment]
@brafdlog Try running it with exact at a short interval (say 1 minute). I don't think 1 min will be enough time for Android to kill your app unless the user is doing something super heavy memory wise, and in effect the app will be on continuously. I would like to keep the `alwaysRunning` option but at the same time this change brings enough improvements for me to motivate merging it. Since I won't be using `alwaysRunning` at my day job I can't allocate time to reimplement it though but would obviously be very happy to merge a PR that readds this feature.

**Comment by vikeri** [comment]
Update: I've been testing this now for a while in our app. I'm having a couple of issues.
- If I kill the app (swipe left on the recent app screen) the exact job are typically not restarted or run again.
- The timeout does not seem to be respected but RN kills the app before the specified timeout. This is not necessarily a bug introduced in this PR though, but might be a larger issue with the library.

**Comment by toteto** [comment]
@vikeri 
- Exact jobs not persisted: what Android version you have tried this? I have tested it on Android 7.1 and it worked even after force stopping the app.
- Timeout not respected: could you please set a breakpoint on [ReactNativeEventStarter.java#41](https://github.com/toteto/react-native-background-job/blob/a698f59857a2284074b073fcb2eaa84749c1ac46/android/src/main/java/com/pilloxa/backgroundjob/ReactNativeEventStarter.java#L41) and check if the correct value is read from the Bundle?

**Comment by vikeri** [comment]
I've been trying this with 7.1, after testing with the example app things seem to work. Will investigate more in our production app.

**Comment by vikeri** [comment]
This is now released as `2.0.0` 🎉

Thanks a lot for the PR @toteto

**Comment by toteto** [comment]
Good to hear that everything has turned out ok. Thanks for support, it was a great experience and i learned a lot during the process about React Native.

**Comment by mauriciopasquier** [comment]
I'm confused by this bit:

> AlarmManager by setting `exact` to `true`: Simple propriatery implementation that is only ment to be used while testing. It only cares about executing on time, all other parameters are ignored - job is not persisted on reboot.

What does it mean by propietary implementation? And how would you set up an alarm (for example) to trigger at a precise time but which is persisted between boots?

**Comment by cbjs** [comment]
any chance to use 2.0.0 on devices without google play service?

**Pull request merged**
